### ISSUE TITLE
Displaylastpost et PHP 8

### ISSUE THREAD

**Issue by Gpinpin** [Aurelienazerty/DisplayLastPost#8]
Hi. Does not work in PHP 8.0.2 for version 1.27
Already in the language files the [] are not used
But probably other problems overall with your version 1.27.
1.2 works with modified files
$lang = [];

$lang = array_merge($lang, [
]);

A+

**Comment by Aurelienazerty** [comment]
I didn't have PHP 8 installed, I'll update a test server.

**Comment by pipetko** [comment]
Not working on last version of phpbb :(

**Comment by Aurelienazerty** [comment]
> 
> 
> Hi. Does not work in PHP 8.0.2 for version 1.27 Already in the language files the [] are not used But probably other problems overall with your version 1.27. 1.2 works with modified files $lang = [];
> 
> $lang = array_merge($lang, [ ]);
> 
> A+

$lang = [];  and $lang = array(); is the same. It's just short syntax array. I don't think this is the point.

**Comment by Aurelienazerty** [comment]
> 
> 
> Not working on last version of phpbb :(

Please make new issue.

**Comment by Aurelienazerty** [comment]
Tested on php 8, work fine. Please update from git.
